runtime: custom
vm: true
api_version: 1
threadsafe: on

manual_scaling:
  instances: 2

resources:
  cpu: 1
  disk_size_gb: 10
  memory_gb: 4

builtins:
- appstats: on

health_check:
  enable_health_check: true
  check_interval_sec: 60
  timeout_sec: 45
  unhealthy_threshold: 4
  healthy_threshold: 2
  restart_threshold: 15

handlers:

# Favicon.  Without this, the browser hits this once per page view.
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

# Main app.  All the real work is here.
- url: /.*
  script: main.application
  # Force HTTPS
  secure: always
  login: admin

